- name: '[Linux] configure ngnix'
  import_playbook: configure_nginx_web_server.yml

- hosts: windows
  gather_facts: false
  roles:
    - chocolatey

- name: '[Windows] configure IIS'
  import_playbook: configure_iis_web_server.yml
